# SELECT PARENT.ID, COUNT(CHILD.ID)
# FROM ECOLI_DATA AS PARENT
# LEFT OUTER JOIN ECOLI_DATA AS CHILD
# ON PARENT.ID = CHILD.PARENT_ID
# GROUP BY PARENT.ID

SELECT PARENT.ID, COUNT(CHILD.ID) AS CHILD_COUNT
FROM ECOLI_DATA AS PARENT
LEFT OUTER JOIN ECOLI_DATA AS CHILD
ON PARENT.ID = CHILD.PARENT_ID
GROUP BY PARENT.ID
ORDER BY ID

-- ID와 PARENT_ID와 비교해서, PARENT_ID가 없을 ID를 생각해서 OUTER JOIN을 한다
-- 비교 값을 ID가 자식의 PARENT_ID일 경우를 JOIN한다.
-- 그럼 각자 자식이 나온다.



# SELECT
#     PARENT.ID,
#     COUNT(CHILD.ID) AS CHILD_COUNT
# FROM
#     ECOLI_DATA AS PARENT
# LEFT OUTER JOIN
#     ECOLI_DATA AS CHILD ON PARENT.ID = CHILD.PARENT_ID
# GROUP BY
#     PARENT.ID
# ORDER BY
#     PARENT.ID