# SELECT ANIMAL_ID, NAME , DATETIME
# FROM ANIMAL_OUTS
# WHERE ANIMAL_ID IN (
#     SELECT ANIMAL_ID 
#     FROM ANIMAL_INS
#     ORDER BY DATETIME DESC)
# LIMIT 2


SELECT O.ANIMAL_ID, O.NAME
FROM ANIMAL_INS AS I
INNER JOIN ANIMAL_OUTS AS O
ON I.ANIMAL_ID = O.ANIMAL_ID
ORDER BY DATEDIFF(O.DATETIME, I.DATETIME) + 1 DESC
LIMIT 2
