-- 1차 시도 : HAVING 절에 MAX(FAVORITES)를 해도 정확한 필터링이 되지 않았다.
-- HAVING 절에는 MAX(FAVORITES) = 어떤 값과 같이 비교 연산자를 사용해야 한다.
# SELECT FOOD_TYPE, REST_ID, REST_NAME, FAVORITES
# FROM REST_INFO
# GROUP BY FOOD_TYPE
# HAVING MAX(FAVORITES)
# ORDER BY FOOD_TYPE DESC


-- 서브쿼리를 사용해야 한다.
SELECT FOOD_TYPE, REST_ID, REST_NAME, FAVORITES
FROM REST_INFO
WHERE (FOOD_TYPE, FAVORITES) IN (
        SELECT FOOD_TYPE, MAX(FAVORITES)
        FROM REST_INFO
        GROUP BY FOOD_TYPE
        )
ORDER BY FOOD_TYPE DESC

# SELECT FOOD_TYPE, REST_ID, REST_NAME, MAX(FAVORITES)
# FROM REST_INFO
# GROUP BY FOOD_TYPE
# ORDER BY FOOD_TYPE DESC