# SELECT
# CASE
# WHEN SEX_UPON_INTAKE IN ('Neutered Male', 'Spayed Female') THEN 'O'
# WHEN SEX_UPON_INTAKE IN ('Intact Male') THEN 'X'
# END
# FROM ANIMAL_INS

SELECT
ANIMAL_ID, NAME,
CASE
WHEN SEX_UPON_INTAKE LIKE '%Neutered%' OR SEX_UPON_INTAKE LIKE '%Spayed %' THEN 'O'
ELSE 'X'
END
AS 중성화
FROM ANIMAL_INS
ORDER BY ANIMAL_ID