SELECT U.USER_ID, U.NICKNAME, SUM(PRICE) AS TOTAL_SALES 
FROM USED_GOODS_BOARD AS B
JOIN USED_GOODS_USER AS U
ON B.WRITER_ID = U.USER_ID
WHERE B.STATUS = 'DONE'
GROUP BY B.WRITER_ID
HAVING TOTAL_SALES >= 700000 -- SELECT의 별칭사용 가능
ORDER BY TOTAL_SALES ASC