# SELECT ITEM_ID, ITEM_NAME, RARITY
# FROM ITEM_INFO 
# WHERE ITEM_ID IN (SELECT ITEM_ID FROM ITEM_INFO WHERE RARITY = 'RARE') AND ITEM_ID IN (SELECT ITEM_ID FROM ITEM_TREE WHERE PARENT_ITEM_ID IS NOT NULL)
# ORDER BY ITEM_ID DESC

-- RARE -> NOT NULL

SELECT INFO.ITEM_ID, INFO.ITEM_NAME, INFO.RARITY
FROM ITEM_INFO AS INFO
JOIN ITEM_TREE AS TREE
    ON INFO.ITEM_ID = TREE.ITEM_ID
WHERE TREE.PARENT_ITEM_ID IN (
    SELECT ITEM_ID
    FROM ITEM_INFO
    WHERE RARITY = 'RARE'
) AND TREE.PARENT_ITEM_ID IS NOT NULL
ORDER BY INFO.ITEM_ID DESC