SELECT MCDP_CD AS '진료과 코드', COUNT(MCDP_CD) AS '5월예약건수' FROM APPOINTMENT 
WHERE YEAR(APNT_YMD) = 2022 and MONTH(APNT_YMD) = 05
GROUP BY MCDP_CD
ORDER BY 2,1
# ORDER BY '5월예약건수' ASC, '진료과 코드' ASC


# SELECT MCDP_CD '진료과 코드', COUNT(APNT_NO) '5월예약건수'
# FROM APPOINTMENT
# WHERE MONTH(APNT_YMD) LIKE '5'
# GROUP BY 1
# ORDER BY 2,1