SELECT SUM(GR.SCORE) AS SCORE, GR.EMP_NO, EM.EMP_NAME, EM.POSITION, EM.EMAIL
FROM HR_DEPARTMENT AS DE
INNER JOIN HR_EMPLOYEES AS EM
ON DE.DEPT_ID = EM.DEPT_ID
INNER JOIN HR_GRADE AS GR
ON EM.EMP_NO = GR.EMP_NO
GROUP BY GR.EMP_NO
ORDER BY SCORE DESC
LIMIT 1
