SELECT B.CATEGORY AS CATEGORY, SUM(SALES) AS TOTAL_SALES
FROM BOOK AS B
INNER JOIN BOOK_SALES AS SALE
ON B.BOOK_ID = SALE.BOOK_ID
WHERE DATE_FORMAT(SALE.SALES_DATE, '%Y-%m') = '2022-01'
GROUP BY B.CATEGORY
ORDER BY CATEGORY ASC


# SELECT B.CATEGORY AS CATEGORY, COUNT(B.CATEGORY) AS TOTAL_SALES
# FROM BOOK AS B
# INNER JOIN BOOK_SALES AS SALE
# ON B.BOOK_ID = SALE.BOOK_ID
# WHERE DATE_FORMAT(SALE.SALES_DATE, '%Y-%m') = '2022-01'
# GROUP BY B.CATEGORY
# ORDER BY CATEGORY ASC